server:
  port: 8083
  servlet:
    contextPath: "/app"

ambiente: local

config:
  origin: 'http://localhost:4200'
  methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'

credenciales:
  host: 'c9pbiquf6p6pfn.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com'
  user: 'uaanq59dnolmqi'
  password: 'p5c91b3e820e78381c6a842c61a70c93e2637c1a3c3aeb4943afe15c7a042b2c9'
  database: 'dcp0tj1o1832v8'
  port: 5432
  ssl:
    rejectUnauthorized: true



# credenciales:
#   host: 'ec2-54-86-106-48.compute-1.amazonaws.com'
#   user: 'yeaqqqxacdvcja'
#   password: 'aadb590438bc25dc9974600f53827f203d174ce44c1af84251f114406517f5d0'
#   database: 'dar3vfiejpldu3'
#   port: 5432
#   ssl:
#     rejectUnauthorized: false






# Nostas

# sol123
# 5435

# server      localhost
# database    postgres
# port        5433
# username    postgres
# password    sol123